name: Node.js CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: nix

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: nix run .#build

      - name: Lint
        run: nix run .#lint
